// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sonata.Server.Data;

#nullable disable

namespace Sonata.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719052952_AddHackathonMemoryPersistence")]
    partial class AddHackathonMemoryPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sonata.Server.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.ToTable("conversations");
                });

            modelBuilder.Entity("Sonata.Server.Models.Memory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_state");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid")
                        .HasColumnName("movement_id");

                    b.Property<Guid>("SourceNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_note_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SourceNoteId")
                        .IsUnique();

                    b.HasIndex("MovementId", "LifecycleState", "CreatedAt");

                    b.ToTable("memories");
                });

            modelBuilder.Entity("Sonata.Server.Models.MemoryUse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MemoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("memory_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reason");

                    b.Property<long>("ResponseMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("response_message_id");

                    b.HasKey("Id");

                    b.HasIndex("MemoryId");

                    b.HasIndex("ResponseMessageId", "MemoryId")
                        .IsUnique();

                    b.ToTable("memory_uses", null, t =>
                        {
                            t.HasCheckConstraint("CK_memory_uses_rank_positive", "rank > 0");
                        });
                });

            modelBuilder.Entity("Sonata.Server.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "Sequence")
                        .IsUnique();

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("CK_messages_sequence_positive", "sequence > 0");
                        });
                });

            modelBuilder.Entity("Sonata.Server.Models.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.ToTable("movements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Qwen AI Hackathon",
                            StartedAt = new DateTimeOffset(new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Sonata.Server.Models.SourceNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("excerpt");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("source_notes");
                });

            modelBuilder.Entity("Sonata.Server.Models.Conversation", b =>
                {
                    b.HasOne("Sonata.Server.Models.Movement", "Movement")
                        .WithMany("Conversations")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("Sonata.Server.Models.Memory", b =>
                {
                    b.HasOne("Sonata.Server.Models.Movement", "Movement")
                        .WithMany("Memories")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonata.Server.Models.SourceNote", "SourceNote")
                        .WithOne("Memory")
                        .HasForeignKey("Sonata.Server.Models.Memory", "SourceNoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("SourceNote");
                });

            modelBuilder.Entity("Sonata.Server.Models.MemoryUse", b =>
                {
                    b.HasOne("Sonata.Server.Models.Memory", "Memory")
                        .WithMany("Uses")
                        .HasForeignKey("MemoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sonata.Server.Models.Message", "ResponseMessage")
                        .WithMany()
                        .HasForeignKey("ResponseMessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Memory");

                    b.Navigation("ResponseMessage");
                });

            modelBuilder.Entity("Sonata.Server.Models.Message", b =>
                {
                    b.HasOne("Sonata.Server.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Sonata.Server.Models.SourceNote", b =>
                {
                    b.HasOne("Sonata.Server.Models.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("Sonata.Server.Models.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Sonata.Server.Models.Memory", b =>
                {
                    b.Navigation("Uses");
                });

            modelBuilder.Entity("Sonata.Server.Models.Movement", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Memories");
                });

            modelBuilder.Entity("Sonata.Server.Models.SourceNote", b =>
                {
                    b.Navigation("Memory");
                });
#pragma warning restore 612, 618
        }
    }
}
